# Generated by Django 4.2.2 on 2023-07-13 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_alter_accion_ticker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('subtitulo', models.CharField(max_length=40)),
                ('autor', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='accion',
            old_name='Empresa',
            new_name='empresa',
        ),
    ]
