# Generated by Django 4.2.2 on 2023-07-15 18:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0007_blog_rename_empresa_accion_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='desarrollo_blog',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='fecha_publicacion',
            field=models.DateField(default='2020-01-01'),
        ),
    ]
