# Generated by Django 4.2.2 on 2023-07-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0010_alter_blog_fecha_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagen_blog'),
        ),
    ]
