# Generated by Django 4.2.2 on 2023-07-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0014_rename_user_infoextrablog_blog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagen_blog'),
        ),
        migrations.DeleteModel(
            name='InfoExtraBlog',
        ),
    ]
