# Generated by Django 4.2.2 on 2023-07-15 23:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoextra',
            name='descripcion',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='infoextra',
            name='pagina_web',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
